version: '2'
services:
  source-dummy_ltsv:
    build:
      context: ./source
    volumes:
    - log:/var/log
    networks:
    - source
  source-fluentd:
    image: fluent/fluentd:latest
    environment:
    - 'FLUENTD_CONF=fluent.conf'
    volumes:
    - ./source/fluent.conf:/fluentd/etc/fluent.conf:ro
    - log:/var/log
    networks:
    - source
  sink-fluentd:
    build:
      context: ./sink
      dockerfile: ./Dockerfile.sink.fluentd
    environment:
    - 'FLUENTD_CONF=fluent.conf'
    volumes:
    - ./sink/fluent.conf:/fluentd/etc/fluent.conf:ro
    - log:/var/log:ro
    networks:
    - sink
  sink-rdb:
    image: postgres
    environment:
    - 'POSTGRES_USER=root'
    - 'POSTGRES_PASSWORD=postgres'
    volumes:
    - ./sink/initdb.d:/docker-entrypoint-initdb.d
    - pgdata:/var/lib/postgresql/data
    networks:
    - sink

volumes:
  log:
    driver: local
  pgdata:
    driver: local
networks:
  source:
  sink:
