version: '2.2'
services:
  source-dummy_ltsv:
    build:
      context: ./source
    volumes:
    - log:/var/log
    networks:
    - source
  source-fluentd:
    build:
      context: ./source
      dockerfile: ./Dockerfile.source.fluentd
    environment:
    - 'FLUENTD_CONF=fluent.conf'
    volumes:
    - ./source/fluent.conf:/fluentd/etc/fluent.conf:ro
    - log:/var/log
    networks:
    - source
    - fluentd
    - dummy_aws
    depends_on:
    - localstack
  sink-fluentd:
    build:
      context: ./sink
      dockerfile: ./Dockerfile.sink.fluentd
    environment:
    - 'FLUENTD_CONF=fluent.conf'
    volumes:
    - ./sink/fluent.conf:/fluentd/etc/fluent.conf:ro
    networks:
    - sink
    - fluentd
  sink-rdb:
    image: postgres
    environment:
    - 'POSTGRES_USER=root'
    - 'POSTGRES_PASSWORD=postgres'
    volumes:
    - ./sink/initdb.d:/docker-entrypoint-initdb.d
    - pgdata:/var/lib/postgresql/data
    networks:
    - sink
  localstack:
    image: localstack/localstack:latest
    environment:
    - 'SERVICES=s3,sqs'
    networks:
    - dummy_aws
    ports:
    - 8080:8080
    - 4567-4578:4567-4578

volumes:
  log:
    driver: local
  pgdata:
    driver: local
networks:
  source:
  sink:
  fluentd:
  dummy_aws:
