version: '2.2'
services:
  source-dummy_ltsv:
    build:
      context: ./source
      dockerfile: ./Dockerfile.dummy.logger
    volumes:
    - log:/var/log
    networks:
    - source
  source-fluentd:
    build:
      context: ./source
      dockerfile: ./Dockerfile.source.fluentd
    environment:
    - 'FLUENTD_CONF=fluent.conf'
    volumes:
    - ./source/fluent.conf:/fluentd/etc/fluent.conf:ro
    - log:/var/log
    networks:
    - source
    - localstack
  sink-fluentd:
    build:
      context: ./sink
      dockerfile: ./Dockerfile.sink.fluentd
    environment:
    - 'FLUENTD_CONF=fluent.conf'
    volumes:
    - ./sink/fluent.conf:/fluentd/etc/fluent.conf:ro
    networks:
    - sink
    - localstack
  sink-rdb:
    image: postgres
    environment:
    - 'POSTGRES_USER=root'
    - 'POSTGRES_PASSWORD=postgres'
    volumes:
    - ./sink/initdb.d:/docker-entrypoint-initdb.d
    networks:
    - sink
  localstack:
    image: localstack/localstack
    environment:
    - 'SERVICES=s3,sqs'
    - 'HOSTNAME_EXTERNAL=localstack'
    ports:
    - 8080:8080
    - 4572:4572
    - 4576:4576
    networks:
    - localstack

volumes:
  log:
    driver: local
networks:
  source:
  sink:
  localstack:
